name: 'Commit Messages Between Commits'
description: 'Generate list of commit messages between two commits'
author: 'Tyler Milner'
inputs:
  begin-sha:
    description:
      'SHA hash for the commit that should be used as the beginning of the
      commit history. Defaults to initial repo commit.'
    required: false
  end-sha:
    description:
      'SHA hash for the commit that should be used as the ending of the commit
      history. Defaults to current commit.'
    required: false
    default: ${{ github.sha }}
  commit-messages-file:
    description: 'File path to save commit messages to.'
    required: false
outputs:
  commit-messages:
    description: 'The commit messages between `begin-sha` and `end-sha`'
    value: ${{ steps.generate-commit-messages.outputs.commit-messages }}
runs:
  using: 'composite'
  steps:
    - name: Generate commit messages
      id: generate-commit-messages
      run: ${{ github.action_path }}/generate-commit-messages.sh
      shell: bash
      env:
        INPUT_BEGIN_SHA: ${{ inputs.begin-sha }}
        INPUT_END_SHA: ${{ inputs.end-sha }}
        INPUT_COMMIT_MESSAGES_FILE: ${{ inputs.commit-messages-file }}
branding:
  icon: 'git-commit'
  color: 'green'
