name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4.1.6

      # Set Git user for commits that will be created when running tests
      - name: Setup Git
        id: setup-git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "<>"

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0 # Fetch full history

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          begin-sha: ${{ github.event.before }}
          end-sha: ${{ github.sha }}
          commit-messages-file: commit-messages.txt

      - name: Print Variable Output
        id: variable-output
        run: |
          echo "Generated commit messages output:"
          cat << EOF
          ${{ steps.test-action.outputs.commit-messages }}
          EOF

      - name: Print File Output
        id: file-output
        run: |
          echo "Contents of commit messages file:"
          cat commit-messages.txt
